# Site settings
title: ANR JCJC I-VESSEG
email: maria.zuluaga@eurecom.fr
description: Website of the ANR JCJC Project I-VESSEG
baseurl: ""
url: ""

# Google analytics ID: Remove or use your own!
#google_analytics: UA-167467135-1
#google_analytics_4: G-02KDGRRB2T
#google_tag_manager: GTM-TZ9Z7HZ

# Footer info
about: >
    Data Science Department
    <a href="https://www.eurecom.fr" target="_blank">EURECOM</a><br/>

information: >
    <a href="mailto:zuluaga@eurecom.fr" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Maria via email</a> <br/>
    <a href="/vacancies.html"><i class="fa fa-users fa-1x"></i> Explore openings</a> <br/>
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: team
  - name: publications
  - name: research
  - name: software

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Zuluaga
  first_name: [Maria A.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
